name = "VTKOutputs"
uuid = "be41f24c-e31d-4e46-8a60-1ebf7af5120a"
authors = ["PenguinxCutCell"]
version = "0.1.0"

[deps]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
WriteVTK = "64499a7a-5c06-52f2-abe2-ccb03c286192"

[compat]
Test = "1.11.0"
WriteVTK = "1.21.2"
julia = "1.10"
